### ISSUE TITLE
Review cardinality restrictions to avoid inconsistent ontology errors. Correct cardinality restrictions.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#105]
Cardinality should be reviewed. "Exactly 1" cardinality will be enforced by some reasoners and throw an ontology or knowledgebase into logical inconsistency if it is not true.

**Comment by sbarnum** [comment]
Not sure what this issue is describing.

Any existing cardinality restrictions (exact, min or max) are asserted intentionally by design to convey the domain context of the properties on the associated classes. They are a fundamental part of the ontology and cannot be removed.

It is certainly possible that there are errors in current cardinality restrictions either at the ontology specification level (conflicting restrictions) or at the domain level (wrong cardinality specified). 
It would be practical to review the ontology to look for and address ontology specification level errors but would not be practical to review for domain level errors. Domain level errors are only going to be revealed by use of the ontology.

Can you give a little more clarity on this issue? Thanks

**Comment by rhohimer** [comment]
Yes, clarity is good, and ambiguity is not!

A review needs to be done to check for cardinality restrictions that may cause a knowledgebase built upon the uco ontology to become logically inconsistent when the restrictions cannot be met. For example, if a restriction states that a property must have a value, and at the time of investigation we don't have a value to assert, the knowledgebase becomes logically inconsistent. Logical consistency is a requisite for a description logic reasoner to make proper inferences. 

It is related to the Open World Assumption. Just because we don't know something, does not mean it is not true, or that it does not exist.

I don't know the extent to which this manifests itself in the UCO ontology currently, but I did see a potential occurance during the workshop. A brief comment was made at the time, which was captured in the "to do" list of clean up. Hence this issue to review UCO for potential problems regarding cardinality.

This is of course different from the Closed World Assumption frequently made in object oriented programming designs.

**Comment by rhohimer** [comment]
Testing cardinality: 
![image](https://user-images.githubusercontent.com/9854293/60628459-5bb17800-9da6-11e9-9d3b-02bb5ca79276.png)

**Comment by rhohimer** [comment]
As it is turning out, the number of cardinality errors seems to be limited. Good news for us... still investigating.

**Comment by rhohimer** [comment]
The cardinality restriction of "exactly 1" does not seem to cause error, or inconsistency when cardinality is 0.  Perhaps this is an Open World Assumption thing, Cardinality restrictions are still concerning me, however, Let's go with what we have and address any bugs if and when they arise.

I'm going to close this issue, review of cardinality will continue. Not Branch or Pull Request was made on this issue.
