### ISSUE TITLE
Add modifiedTime property to UCOObject 

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#164]
To support practical versioning of objects as they evolve and change, propose the addition of the following new property as required on UCOObject:
core:modifiedTime
a owl:DatatypeProperty
rdfs:comment """Specifies the time that this particular version of the object was modified. The object creator can use the time it deems most appropriate as the time this version of the object was modified. The value of the modified property for a given object version MUST be later than or equal to the value of the created property.
Object creators MUST update the modified property when creating a new version of an object.
The modified timestamp MUST be precise to the nearest millisecond (exactly three digits after the decimal place in seconds)."""@en-us ;
rdfs:range xsd:dateTime

This issue was broken out from Issue #158

**Comment by sbarnum** [comment]
Potential solution in branch Issue-164-sdb

**Comment by ajnelson-nist** [comment]
I can see this timestamp being populated directly from data sources instead of from the triple generator's current clock.  Is this property meant to ONLY be populated by the generating program, and NEVER from source data?

I also suggest that the timestamp not be limited to the nearest millisecond.  Shouldn't I as an overly-careful triple generator be allowed to record a timestamp more precise than a millisecond?

**Comment by ehazard-mitre** [comment]
This issue has been changed to "committed" due to the merge of PR #173 into branch develop. It's now staged for merging into master (for 0.4.0 release).

**Comment by sbarnum** [comment]
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0
