### ISSUE TITLE
Domain assertion of observable:emailAddress is too restrictive

### ISSUE THREAD

**Issue by ajnelson-nist** [ucoProject/UCO#183]
I stumbled on this while aligning the CASE example `accounts.json` with UCO 0.3.0.  This is also true for today's state of `develop`.

`observable:emailAddress` is a property of the `observable:EmailAccount` facet.  However, the definition of the property states its domain is the facet `observable:WhoisContactType`; this domain definition was carried into `observable-da.ttl`.  Poking around `observable.ttl`, I see `emailAddress` is also a property of `WhoisRegistrarInfoType`.

The domain assertion is incorrectly restrictive, and should either be expanded or removed.

This somewhat relates to [Issue 25](https://github.com/ucoProject/UCO/issues/25).

**Comment by rhohimer** [comment]
@ajnelson-nist Yes, this, and many others like it, is why separating these domain assertions the way we resently did was important to do.  In the example you cite here any time the observable:emailAddress in used the subject of the triple will be asserted to be of rdf:type EmailAddress AND WhoisRegistryInfoType.  It is not logical. Hence, logically inconsistent.

So, since I believe these domain assertions are wrong, adopters like DarkLight should not import the observable-da.ttl file.  Or any of the xxxx-da.ttl files, in my opinion. If they do, they cannot use an inferencing engine (reasoner).

**Comment by sbarnum** [comment]
This issue will be addressed through implementation of
JIRA OC-68: https://unifiedcyberontology.atlassian.net/browse/OC-68
and CP-13: https://unifiedcyberontology.atlassian.net/wiki/spaces/OC/pages/984678401/UCO+CP-23+Convert+current+property+restrictions+and+domain+assertions+to+SHACL+shapes
