### ISSUE TITLE
Can't read ontologies into Protege

### ISSUE THREAD

**Issue by jlloganiii** [ucoProject/UCO#249]
What are the steps to import these ontologies into Protege? I've been struggling with XML catalog and null pointer exceptions.

**Comment by ajnelson-nist** [comment]
Hi @jlloganiii ,

We are working on making these network accessible so a user can retrieve the ontology files by pointing at the ontology's IRI.

For now, the way I've found Protege will work is to:
1. git-clone this repository.
2. Open `uco-master/uco.ttl` with Protege.
3. Protege will complain about some ontology IRIs not being accessible, and ask you to resolve them yourself with a local file reference.  This will be a couple clicks per `.ttl` file, but will populate the file `uco-master/catalog-v001.xml`.  Keep that file around in your checkout - Protege uses it to remember the IRI--file associations.  You won't need to do these clicks again as long as that file's present.

It does not seem like that file can be version-controlled for the general convenience of Protege users, because the file paths it logs are absolute paths, including user shell name.  To be even feasible to consider tracking, there would need to be some mechanism to define a variable in the XML to enable pathing relative to the catalog file's location; and even then, UCO's ontology committee would need to consider supporting the catalog as an artifact to the benefit of (to my knowledge) a sole tool.  I don't speak for the committee, but that is the hill up which a proposal would need to climb.

We hope for this issue to be moot soon, for Protege and for other tools, once the ontologies are network accessible.

Meanwhile, if you are interested in documentation more pleasing to the eye than raw Turtle data, you can find a render of UCO 0.6.0 here:
https://unifiedcyberontology.org/releases/0.6.0/docs/index.html

**Comment by ajnelson-nist** [comment]
We have a potential resolution for this matter (tracking on UCO's Jira: OC-180).  Does this file happen to work for you?

https://github.com/DrSnowbird/UCO/blob/master/catalog-v001.xml

**Comment by ajnelson-nist** [comment]
Hello @jlloganiii ,

UCO now deploys web-retrieval ontology resources that should load with Protégé.

[Issue 449](https://github.com/ucoProject/UCO/issues/449) has been filed to make offline Protégé interaction an option.

**Comment by ajnelson-nist** [comment]
I just stumbled across this Issue and saw it's still open.  With the resolution of #449 , I believe this is resolved.  Please do re-open if you have any outstanding issues.
