### ISSUE TITLE
Upgrade rdf-toolkit and Java

### ISSUE THREAD

**Issue by b0bkaT** [ucoProject/UCO#373]
# Background

# Requirements

## Requirement 1
<p>The CI currently uses rdf-toolkit version 1.8, but version 1.10 is available. UCO should upgrade rdf-toolkit to version 1.10 and in turn upgrade to at least Java 11 (minimum requirement for using rdf-toolkit 1.10).</p>

# Risk / Benefit analysis

## Benefits
<p>UCO's CI will be utilizing the latest version of rdf-toolkit. Additionally, JRE 8 is end-of-life.</p>

## Risks
*  Java 11 does not work on prior rdf-toolkit versions.
*  All of UCO's and CASE resources that use rdf-toolkit currently inherit CASE's original adoption of rdf-toolkit.  Hence, they currently require Java 8. So, this will have downstream effects - those repositories, and any adopters who followed the same practice, will need to rework their environments to include Java >= 11.
*  According to various sources: the end-of-life for Java 11 is Sept. 30, 2023. So, this puts UCO in another near-EOL situation.  Testing should be done to review `rdf-toolkit` compatibility with Javas > 11.

# Competencies demonstrated

## Competency 1

<p>N/A</p>

# Solution suggestion

* Upgrade Java from v8 to v11 in CI workflow.
* Pin version 1.11.0 of rdf-toolkit using current `lib/Makefile` and recorded SHA2-512 hash.
* Revise all references to `rdf-toolkit` *within CASE* to use UCO as imported as a submodule.  This is an expansion of responsibility of a UCO issue, creeping into CASE, but is seen as necessary to keep a shared technology synchronized.
* The solution is implemented for UCO in [PR 398](https://github.com/ucoProject/UCO/pull/398).
* The solution is implemented for CASE in [PR 90](https://github.com/casework/CASE/pull/90).

# Coordination

- Tracking in Jira ticket [OC-235](https://unifiedcyberontology.atlassian.net/browse/OC-235)
- [x] Administrative review to be completed
- [x] Requirements to be discussed in Ontology Committee (OC) meeting, [2022-05-05](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2009825281/2022-05-05+CDO+Ontology+Committees
)
- [x] Requirements Review vote occurred, passing, on 2022-05-17
- [x] *Requirements development phase completed.*
- [x] Solution announced to OCs on 2022-05-28
- [x] Solutions Approval to be discussed in OC meeting, [2022-06-02](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2017394689/2022-06-02+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2022-06-13
- [x] *Solutions development phase completed.*
- [x] Implementation for UCO [merged](https://github.com/ucoProject/UCO/pull/398) into `develop`
- [x] Implementation for CASE [merged](https://github.com/casework/CASE/pull/90) into `develop`
- [x] Milestone linked in UCO
- [x] Milestone linked in CASE
- [x] Documentation logged in pending release page for UCO
- [x] Documentation logged in pending release page for CASE

**Comment by ajnelson-nist** [comment]
Some discussion is happening w.r.t. risks.  A comment will come when that's done being updated.

**Comment by ajnelson-nist** [comment]
Risks have been updated.

**Comment by ajnelson-nist** [comment]
Requirement 1 was revised to say we should upgrade to **at least** Java 11, not necessarily exactly Java 11.

**Comment by ajnelson-nist** [comment]
The solution is posted, and interestingly `pre-commit` caught a normalization update that `observable.ttl` needed.

**Comment by ajnelson-nist** [comment]
The initial solution's scope has been narrowed on encountering an issue with `rdf-toolkit` that, when called via `pre-commit`', prevented `git commit` from working.  Documentation is on [CASE-Examples PR 75](https://github.com/casework/CASE-Examples/pull/75).  The `Makefile` strategy is no longer being replaced with `pre-commit`.

**Comment by ajnelson-nist** [comment]
Something the CASE OC should address is whether the CASE retrieval of `rdf-toolkit.jar` should be erased, and instead solely rely on UCO's implementation.  The logistical trades are:
1. Less code to manage - there would only be one normalization resource for both CASE and UCO, UCO's copy of `rdf-toolkit.jar`.
2. More Git submoduling - Any codebase normalizing Turtle and wanting to use CASE's normalization procedure would need to initialize CASE's submodule of UCO in order to retrieve `rdf-toolkit.jar`, which is a cost of another ~60MB network traffic per fresh clone.  In terms of current `make` recipes, this can be done with 0 code impact to code bases that currently use CASE's retrieval of `rdf-toolkit.jar`.  (CASE's `.lib.done.log` `Makefile` target can be reduced to running UCO's `.lib.done.log` target.)

**Comment by ajnelson-nist** [comment]
On starting testing-review of the implementation, I realized CASE would fall out of sync in Java support if it was not upgraded as part of this ticket.  Due to needing to synchronize dependency of a core maintenance technology (a programming language version), this UCO issue now spans its implementation responsibility downstream into CASE.

If this is a significant concern before opening for a Solutions Approval vote, please provide feedback.

**Comment by plbt5** [comment]
@ajnelson-nist : I didn't pay sufficient attention, and assumed that this applied to both UCO and CASE. I wouldn't call the Java and toolkit upgrade a significant concern for CASE, but we need to appropriately communicate this to the CASE community. So unless the CASE community was already informed simultaneously with UCO, I'd suggest to distribute this to the CASE community as a CASE vote for next CD-OC.

**Comment by ajnelson-nist** [comment]
@plbt5 - this was announced to the CASE and UCO Ontology Committees simultaneously.

**Comment by ajnelson-nist** [comment]
[PR 398](https://github.com/ucoProject/UCO/pull/398) has had its review checklist completed.
