### ISSUE TITLE
Not All Properties Contain Types

### ISSUE THREAD

**Issue by kchason** [ucoProject/UCO#487]
# Untyped Properties in UCO

During the generation of automated CASE Bindings, it was discovered that 2 properties do not contain types and per discussion with @ajnelson-nist, default to an unrestricted range. 

These properties are:
* [`uco-observable:destinationFlags`](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L10171)
* [`uco-observable:byteStringValue`](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L9638)

# Coordination

- Tracking in Jira ticket [OC-280](https://unifiedcyberontology.atlassian.net/browse/OC-280)
- [x] Administrative review completed, proposal announced to Ontology Committees (OCs) on 2022-11-07
- [x] Solution announced to OCs on 2022-11-07
- [x] Solutions Approval to be discussed in OC meeting, [2022-11-17](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2044985374/2022-11-17+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, passing, on 2022-11-17
- [x] *Solutions development phase completed.*
- [x] [Implementation](https://github.com/ucoProject/UCO/pull/490) merged into `develop`
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by ajnelson-nist** [comment]
We will treat this as a fast-track vote, rather than a bugfix.  What nudged it just over the line for me was:

* In a broad sense, adding constraints where there were none before is a backwards-incompatible change.  Users no longer have total freedom to supply anything they want in those properties, such as "☃" (unicode snowman) for `observable:destinationFlags`.  But, absence of a constraint was a bug.
   - Do we have any community members interested in posting a UCO review shape to catch this class of bug---that is, confirming that every `owl:DatatypeProperty` has a range, and that there is at least one `sh:PropertyShape` with that range as a constraint?  (Any who try this should limit the review to be for `rdfs:range`s that are IRIs, not blank nodes.)
* Looking at the datatypes supplied in the PR's first patch, I saw fit to use other datatypes, including one UCO has not used to date.  See [this commit](https://github.com/kchason/UCO/commit/347b3e0f65c340169ba71ec9ec8c41d84567cccd) for documentation.

So, we should have a chance to discuss this before voting in the fix for the missing-constraints bug.
