### ISSUE TITLE
Question about missing classes

### ISSUE THREAD

**Issue by JaimeC98** [ucoProject/UCO#523]
Hi,
I am going to use UCO ontology in a project for University. I have read a paper (https://www.researchgate.net/publication/287195565_UCO_A_Unified_Cybersecurity_Ontology) that talks about classes in UCO like Means, Attacker, Exploit, Consequences, ... But I can't find these classes in UCO, and I don't if is an error of the paper, of UCO or mine. If someone can help meI would be very grateful.

**Comment by ajnelson-nist** [comment]
Hello @JaimeC98 ,

That is a different project.  The UCO you posted this issue on is "The Unified Cyber Ontology", with home page here:

https://unifiedcyberontology.org/

The paper you referenced discusses the "Unified Cyber**security** Ontology" (emphasis added), which by my current understanding has its GitHub project here:

https://github.com/Ebiquity/Unified-Cybersecurity-Ontology

These two projects share an acronym, but otherwise have no overlap.

If that answers your question, please feel free to close the issue.

**Comment by ajnelson-nist** [comment]
Pardon, one adjustment - there is no overlap of personnel.  There is likely significant, but not complete (per your question), overlap of concept coverage.  I am not aware of a comparison between the two efforts.

**Comment by ajnelson-nist** [comment]
Hello @JaimeC98 ,

If you have no further comments on this Issue, would you mind closing it?  Otherwise I will consider this resolved and close it early Monday.
