### ISSUE TITLE
Fix punning errors

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#72]
There are numerous punning errors throughout UCO.

Each instance needs evaluated to decide appropriate "fix" from options below:

- keep DatatypeProperty and discard ObjectProperty
- keep ObjectProperty and discard DatatypeProperty
- Change name of DatatypeProperty
- Change name of ObjectProperty
- refactor current structures to remediate punning issue

[Redeclaration-Removal-No-Pun-Intended.docx](https://github.com/ucoProject/UCO/files/2967167/Redeclaration-Removal-No-Pun-Intended.docx)

**Comment by sbarnum** [comment]
This issue was raised by DarkLight

**Comment by sbarnum** [comment]
The large majority of the reported punning errors do not look to be actual errors as only a DatatypeProperty exists and no ObjectProperty

Actual errors discovered so far include:
observable:password
observable:values
observable:messageID
observable:domain
observable:creator
observable:phoneNumber

**Comment by rhohimer** [comment]
The document Redeclaration-Removal-No-Pun-Intended.docx individually calls out the ObjectProperties and DataProperties that have the same name. There are many more than six. I agree with sbarnum's assessment of the appropriate fix.
Without addressing the root cause of the problem and deciding on which property to discard. All object properties could be renamed by adding a suffix such as Obj.
observable:passwordObj
This removes the OWL 2 violation, but does not clarify the intent of which property type was intended for what use.
