### ISSUE TITLE
core:name should have a range of xsd:string

### ISSUE THREAD

**Issue by sbarnum** [ucoProject/UCO#99]

**Comment by rhohimer** [comment]
the DataProperty name is currently defined in observable rather than name.

![image](https://user-images.githubusercontent.com/9854293/60823994-a8f26880-a15d-11e9-90f1-a3074edaa812.png)

It seem to have the proper Range.

**Comment by sbarnum** [comment]
The issue is that core:name in core.ttl should be a DatatypeProperty of range xsd:string and not an ObjectProperty of range UcoObject.
It is currently modeled incorrectly.

**Comment by rhohimer** [comment]
Since we have the **_observable:name_** DataProperty, I have an issue with having two DataProperty definitions with the same name in different namespaces ...    **_observabel:name_** and **_core:name_**

**Comment by sbarnum** [comment]
While it is preferable to avoid such cases it is perfectly valid for them to exist and one of the main reasons to use namespaces. 
In this case, I think we can avoid the issue by changing the name of observable:name to observable:sectionName

**Comment by rhohimer** [comment]
Okay, I can make that happen, I'll change the observable:name to observable:sectionName, the change the ObjectProperty to a DataProperty on core:name

Namespaces are used to avoid name collisions, that is true. However, by design using namespaces to differentiate between DataProperty definitions in the same ontology is confusing for users. If the intent is to use different namespaces because each use of the predicate has a different domain or range, that forces a user to know the difference. Users are typically not computer scientists and will improperly assert instances.

I am not a fan at all of the current namespaces. They are unnecessary and confusing to users.

**Comment by sbarnum** [comment]
It turns out that observable:name is used by several other classes in addition to WindowsPESection so renaming it to sectionName is not appropriate or adequate.

Each of the uses is for a generic name so I believe the appropriate solution is to just use core:name and remove observable:name.

**Comment by sbarnum** [comment]
PR "Modifications to address issue #99" issued with appropriate changes

**Comment by sbarnum** [comment]
Resolved in PR #107
